### ISSUE TITLE
500 exception on search

### ISSUE THREAD

**Issue by retog** [plazi/goldengate-docker#2]
When searching for a genus on my test instance I get an HTTP 500 Response, with the following exception shown in the body of the response:
```
java.io.IOException
	de.uka.ipd.idaho.goldenGateServer.srs.client.GoldenGateSrsClient.getDocumentResult(GoldenGateSrsClient.java:953)
	de.uka.ipd.idaho.goldenGateServer.srs.client.GoldenGateSrsClient.searchDocumentData(GoldenGateSrsClient.java:840)
	de.uka.ipd.idaho.goldenGateServer.srs.client.GoldenGateSrsClient.searchDocumentData(GoldenGateSrsClient.java:836)
	de.uka.ipd.idaho.goldenGateServer.srs.webPortal.SearchPortalDataManager.searchDocumentData(SearchPortalDataManager.java:194)
	de.uka.ipd.idaho.goldenGateServer.srs.webPortal.SearchPortalServlet.doHtmlRequest(SearchPortalServlet.java:1044)
	de.uka.ipd.idaho.goldenGateServer.srs.webPortal.SearchPortalServlet.doPost(SearchPortalServlet.java:426)
	de.uka.ipd.idaho.goldenGateServer.srs.webPortal.AbstractSrsWebPortalServlet.doGet(AbstractSrsWebPortalServlet.java:92)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
```

In the standard output I see the following on every such request:
```
Request accept content type is text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Error handling request - java.lang.NullPointerException (null)
java.lang.NullPointerException
	at de.uka.ipd.idaho.goldenGateServer.plazi.srs.TaxonomicNameIndexer.getNameResult(TaxonomicNameIndexer.java:513)
	at de.uka.ipd.idaho.goldenGateServer.plazi.srs.TaxonomicNameIndexer.processQuery(TaxonomicNameIndexer.java:355)
	at de.uka.ipd.idaho.goldenGateServer.srs.GoldenGateSRS.searchDocumentNumbers(GoldenGateSRS.java:4716)
	at de.uka.ipd.idaho.goldenGateServer.srs.GoldenGateSRS.searchDocumentData(GoldenGateSRS.java:3790)
	at de.uka.ipd.idaho.goldenGateServer.srs.GoldenGateSRS.searchDocumentData(GoldenGateSRS.java:3747)
	at de.uka.ipd.idaho.goldenGateServer.srs.GoldenGateSRS$9.performActionNetwork(GoldenGateSRS.java:663)
	at de.uka.ipd.idaho.goldenGateServer.GoldenGateServerComponent$ComponentActionNetwork.performActionNetwork(GoldenGateServerComponent.java:159)
	at de.uka.ipd.idaho.goldenGateServer.GoldenGateServer$ServiceRequest.execute(GoldenGateServer.java:986)
	at de.uka.ipd.idaho.goldenGateServer.GoldenGateServer$ServiceThread.run(GoldenGateServer.java:852)
SRS Collection Packer: starting export
java.lang.NullPointerException while exporting collection: null
java.lang.NullPointerException
SRS Collection Packer: starting export
java.lang.NullPointerException while exporting collection: null
java.lang.NullPointerException
```

**Comment by gsautter** [comment]
Solved:
(1) added synonym lookup providers to installation package (to solve this particular case)
(2) hardened taxonomic name indexer against absence of synonym lookup providers (to add flexibility for future applications)
